original_image_path: 'npu_input.png' #'/images/test3.jpg' #Please end the path with '/'if you want to preprocess mutiple images which on the same dir at one time. 
original_image_channel: '3'
mean: '0' #Same arguments can be default.eg: input channels like 3,3,1. The input1 and input2 have same channel amounts and they can share mean and scale.   
scale: '1'
standardization: '1'  #between 1 and 255
mask_flag: false
padding_data: 0
channel_format: 'channel_first' #Indicates channel format
data_type: 'uint8' #float or fp16 or int8 or uint8
raw_datatype: 'not_use' # If the image type you want to preprocessing is raw you need give the input image data type eg:float or fp16 or int8 or uint8 or not_use
normalization_flag: true # Normalization flag that indicates that wether raw images and masking images need to be Normalized or not.
