mixed_precision_type: 'manual' # [str] The type of running mode. 'manual' for general, 'auto' for automatic. Possible: 'auto', 'manual'.

calibration_mode: 'default' # [str] The mode for quantization calibration. Possible: 'default', 'auto'.
                            # If `auto`, it'll select highest SNR calibration method for weight and activation respectively.
                            # If `default`, it'll use `calibration_method` specified below.
# Calibration
calibration_method: 'minmax' # [str] or Dict[str, str] The method for quantization calibration. Possible: 'minmax', 'percentile', 'histogram_enhanced'.
# calibration_method: {"weight": "minmax", "activation": "percentile"}

calibration_data_path: 'Config/DATA' # [str] The folder path of the calibration dataset.
calibration_args: {seed: 42, samples: 1} # [dict] Arguments for the calibration pipeline, e.g., {"seed": 42, "sample": 10}.

# Quantization Precision
skip_quantization: false # [bool] Whether to skip the quantization process. Used for generating FP32/FP16 SNC models.
input_dtype: {} # [Dict[str, str]] A dictionary specifying the data type for each input of the quantized model. e.g., {"input_1": "float32"}
output_dtype: {} # [Dict[str, str]] A dictionary specifying the data type for each output of the quantized model. e.g., {"output_1": "float32"}

# Mixed Precision
mpq_name_dict: {} # [Dict[str, Any]] Name-based dictionary for mixed precision. Key: weight/activation name, Value: bit-width.
mpq_operator_dict: {} # [Dict[str, Any]] Operator-based dictionary for mixed precision. Key: operator type, Value: bit-width.

# Blockwise Quantization
apply_blockwise_quantization: false # [bool] Whether to apply blockwise quantization.
block_size: 64 # [int] The size of the block for blockwise quantization.
bwq_bitwidth: 4 # [int] The bitwidth for blockwise quantization.
skip_bwq_list: [] # [list[str]] The list of names of weights to skip blockwise quantization.

# Automatic Mixed Precision (AMP)
amp_auto_config: true # [bool] Whether to set AMP parameters automatically. If False, you can set parameters following the user guide.

# FP16 AMP
fp16_amp: false # [bool] Whether to use FP16 AMP. It'll set 5% of weights and activations to FP16 by default.

# Advanced Algorithms
advanced_quantization_algorithm:      # [str] The advanced quantization algorithm to apply. Possible: 'smoothquant', 'adaround'.
add_dummy_conv: false # [bool] If True, applies the dummy convolution algorithm to reduce quantization error in residual connections.

# Weight Handling
freeze_weight: false # [bool] If True, indicates that the model weights are frozen and should not be modified.
freeze_weight_encodings_path:      # [str] Path to the encodings file for the frozen weights.

# Debugging & Other
debug_dict: {} # [Dict[str, Any]] A dictionary to apply custom precision to specific activations and weights for debugging.
