feat_extract.0.main.0.weight_22: NPU
s1.2.main.0.weight_152: NPU
DWCONV485_0_160_0: NPU
'112_23': NPU
'258_153': NPU
SCM2.main.0.main.0.weight_2: NPU
'92_3': NPU
SCM2.main.1.main.0.weight_4: NPU
'94_5': NPU
SCM2.main.2.main.0.weight_6: NPU
'96_7': NPU
SCM2.main.3.main.0.weight_8: NPU
'98_9': NPU
'99_10': NPU
DWCONV490_1_161_0: NPU
Encoder.0.layers.0.main.0.main.0.weight_24: NPU
'114_25': NPU
Encoder.0.layers.0.main.1.main.0.weight_26: NPU
CatFor116_27_162: NPU
SCM1.main.0.main.0.weight_12: NPU
'102_13': NPU
SCM1.main.1.main.0.weight_14: NPU
'104_15': NPU
SCM1.main.2.main.0.weight_16: NPU
'106_17': NPU
SCM1.main.3.main.0.weight_18: NPU
'108_19': NPU
'109_20': NPU
SCM1.conv.main.0.weight_21: NPU
SCM2.conv.main.0.weight_11: NPU
CONV4116_27_162_0: NPU
Encoder.0.layers.1.main.0.main.0.weight_28: NPU
'118_29': NPU
Encoder.0.layers.1.main.1.main.0.weight_30: NPU
CatFor120_31_164: NPU
CONV4120_31_164_0: NPU
Encoder.0.layers.2.main.0.main.0.weight_32: NPU
'122_33': NPU
Encoder.0.layers.2.main.1.main.0.weight_34: NPU
CatFor124_35_166: NPU
CONV4124_35_166_0: NPU
Encoder.0.layers.3.main.0.main.0.weight_36: NPU
'126_37': NPU
Encoder.0.layers.3.main.1.main.0.weight_38: NPU
CatFor128_39_168: NPU
CONV4128_39_168_0: NPU
feat_extract.1.main.0.weight_40: NPU
'130_41': NPU
'131_42': CU
FAM2.merge.main.0.weight_43: NPU
CatFor133_44_170: NPU
CONV4133_44_170_0: NPU
Encoder.1.layers.0.main.0.main.0.weight_45: NPU
'135_46': NPU
Encoder.1.layers.0.main.1.main.0.weight_47: NPU
CatFor137_48_172: NPU
CONV4137_48_172_0: NPU
Encoder.1.layers.1.main.0.main.0.weight_49: NPU
'139_50': NPU
Encoder.1.layers.1.main.1.main.0.weight_51: NPU
CatFor141_52_174: NPU
CONV4141_52_174_0: NPU
Encoder.1.layers.2.main.0.main.0.weight_53: NPU
'143_54': NPU
Encoder.1.layers.2.main.1.main.0.weight_55: NPU
CatFor145_56_176: NPU
CONV4145_56_176_0: NPU
Encoder.1.layers.3.main.0.main.0.weight_57: NPU
'147_58': NPU
Encoder.1.layers.3.main.1.main.0.weight_59: NPU
CatFor149_60_178: NPU
CONV4149_60_178_0: NPU
feat_extract.2.main.0.weight_61: NPU
'151_62': NPU
'152_63': CU
FAM1.merge.main.0.weight_64: NPU
CatFor154_65_180: NPU
CONV4154_65_180_0: NPU
Encoder.2.layers.0.main.0.main.0.weight_66: NPU
'156_67': NPU
Encoder.2.layers.0.main.1.main.0.weight_68: NPU
CatFor158_69_182: NPU
CONV4158_69_182_0: NPU
Encoder.2.layers.1.main.0.main.0.weight_70: NPU
'160_71': NPU
Encoder.2.layers.1.main.1.main.0.weight_72: NPU
CatFor162_73_184: NPU
CONV4162_73_184_0: NPU
Encoder.2.layers.2.main.0.main.0.weight_74: NPU
'164_75': NPU
Encoder.2.layers.2.main.1.main.0.weight_76: NPU
CatFor166_77_186: NPU
CONV4166_77_186_0: NPU
Encoder.2.layers.3.main.0.main.0.weight_78: NPU
'168_79': NPU
Encoder.2.layers.3.main.1.main.0.weight_80: NPU
CatFor170_81_188: NPU
CONV4170_81_188_0: NPU
DWDECONV4185_84_192_0: NPU
DWDECONV4190_85_193_0: NPU
DWDECONV4180_83_191_0: NPU
'195_90': NPU
AFFs.0.conv.0.main.0.weight_91: NPU
'197_92': NPU
AFFs.0.conv.1.main.0.weight_93: NPU
DWCONV4175_82_190_0: NPU
'191_86': NPU
AFFs.1.conv.0.main.0.weight_87: NPU
'193_88': NPU
AFFs.1.conv.1.main.0.weight_89: NPU
Decoder.0.layers.0.main.0.main.0.weight_94: NPU
'200_95': NPU
Decoder.0.layers.0.main.1.main.0.weight_96: NPU
CatFor202_97_194: NPU
CONV4202_97_194_0: NPU
Decoder.0.layers.1.main.0.main.0.weight_98: NPU
'204_99': NPU
Decoder.0.layers.1.main.1.main.0.weight_100: NPU
CatFor206_101_196: NPU
CONV4206_101_196_0: NPU
Decoder.0.layers.2.main.0.main.0.weight_102: NPU
'208_103': NPU
Decoder.0.layers.2.main.1.main.0.weight_104: NPU
CatFor210_105_198: NPU
CONV4210_105_198_0: NPU
Decoder.0.layers.3.main.0.main.0.weight_106: NPU
'212_107': NPU
Decoder.0.layers.3.main.1.main.0.weight_108: NPU
CatFor214_109_200: NPU
CONV4214_109_200_0: NPU
feat_extract.3.main.0.weight_110: NPU
'216_111': NPU
'217_112': NPU
Convs.0.main.0.weight_113: NPU
'219_114': NPU
Decoder.1.layers.0.main.0.main.0.weight_115: NPU
'221_116': NPU
Decoder.1.layers.0.main.1.main.0.weight_117: NPU
CatFor223_118_202: NPU
CONV4223_118_202_0: NPU
Decoder.1.layers.1.main.0.main.0.weight_119: NPU
'225_120': NPU
Decoder.1.layers.1.main.1.main.0.weight_121: NPU
CatFor227_122_204: NPU
CONV4227_122_204_0: NPU
Decoder.1.layers.2.main.0.main.0.weight_123: NPU
'229_124': NPU
Decoder.1.layers.2.main.1.main.0.weight_125: NPU
CatFor231_126_206: NPU
CONV4231_126_206_0: NPU
Decoder.1.layers.3.main.0.main.0.weight_127: NPU
'233_128': NPU
Decoder.1.layers.3.main.1.main.0.weight_129: NPU
CatFor235_130_208: NPU
CONV4235_130_208_0: NPU
feat_extract.4.main.0.weight_131: NPU
'237_132': NPU
'238_133': NPU
Convs.1.main.0.weight_134: NPU
'240_135': NPU
Decoder.2.layers.0.main.0.main.0.weight_136: NPU
'242_137': NPU
Decoder.2.layers.0.main.1.main.0.weight_138: NPU
CatFor244_139_210: NPU
CONV4244_139_210_0: NPU
Decoder.2.layers.1.main.0.main.0.weight_140: NPU
'246_141': NPU
Decoder.2.layers.1.main.1.main.0.weight_142: NPU
CatFor248_143_212: NPU
CONV4248_143_212_0: NPU
Decoder.2.layers.2.main.0.main.0.weight_144: NPU
'250_145': NPU
Decoder.2.layers.2.main.1.main.0.weight_146: NPU
CatFor252_147_214: NPU
CONV4252_147_214_0: NPU
Decoder.2.layers.3.main.0.main.0.weight_148: NPU
'254_149': NPU
Decoder.2.layers.3.main.1.main.0.weight_150: NPU
CatFor256_151_216: NPU
CONV4256_151_216_0: NPU
CatFor259_154_218: NPU
CONV4259_154_218_0: NPU
DWDECONV4264_155_220_0: NPU
last_conv.0.main.0.weight_156: NPU
'266_157': NPU
last_conv.1.main.0.weight_158: NPU
'268_159': NPU
feat_extract.0.main.0.weight_22_DOWNSAMPLE: CPU
output_160_UPSAMPLE: CPU
