ground_truth_path: DATA/GroundTruth               #[path]: the ground truth path (default path is {workspace}/DATA/GroundTruth)
model_type: classification                        #[classification, detection, segmentation, superresolution]: Provide accuracy report (classification model: top1 and top5, detection model: mAP, semantic segmentation model: mIoU, superresolution model: PSNR)
class_mappings:
  Head: 3
  Object: 1
  Person: 2
  Text: 4
conf-thresholds: '1e-2'
#For MCD model the conf-thresholds should be like:
#conf-thresholds:
# 1: 0.3
# 2: 0.3
# 3: 0.3
# 4: 0.3
enable_small_medium_large_box_eval: 'False'
iou-threshold: 0.3
npu_output_dtype: 'float32'
models_structure: 'public'   ##[public, private]: Model structure modification: we now only support the public version models(without structure changes) which
                             ## from Inception family, Mobiledet_SSD family, Mobilenet_Edgetpu family, Mobile_Segmenter family if you 
                             ##are the outside user of samsung. Please set it as private if you are the samsung user else.
